import 'recipe_models.dart';

/// Indian-cuisine PCOS-friendly recipes.
final List<PcosRecipe> indianRecipes = [
  PcosRecipe(
    id: 'in_moong_dal_chilla',
    title: 'Moong Dal Chilla (Savory Lentil Crepe)',
    cuisine: Cuisine.indian,
    mealType: MealType.breakfast,
    tags: [PcosTag.highProtein, PcosTag.lowGi, PcosTag.highFiber],
    description: 'A protein-rich, low-GI alternative to rice or wheat-based breakfasts, popular across North India.',
    prepMinutes: 15,
    cookMinutes: 15,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Split yellow moong dal (washed)', amount: '1 cup', note: 'soaked 3+ hours'),
      RecipeIngredient(name: 'Onion, finely chopped', amount: '1 small'),
      RecipeIngredient(name: 'Tomato, finely chopped', amount: '1 small'),
      RecipeIngredient(name: 'Green chili, minced', amount: '1'),
      RecipeIngredient(name: 'Ginger, grated', amount: '1 tsp'),
      RecipeIngredient(name: 'Cumin seeds', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Turmeric powder', amount: '1/4 tsp'),
      RecipeIngredient(name: 'Fresh coriander, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Salt', amount: 'to taste'),
      RecipeIngredient(name: 'Olive oil or ghee', amount: '1 tbsp', note: 'for cooking'),
    ],
    steps: const [
      'Drain the soaked moong dal and blend with about 1/2 cup water, cumin seeds, and turmeric into a smooth, pourable batter.',
      'Stir in the onion, tomato, green chili, ginger, coriander, and salt.',
      'Heat a non-stick or cast-iron pan on medium and lightly grease with oil.',
      'Pour a ladle of batter and spread thin in a circular motion, like a crepe.',
      'Drizzle a few drops of oil around the edges and cook 2–3 minutes until the base is golden, then flip and cook the other side.',
      'Serve hot with mint chutney or plain yogurt.',
    ],
    whyItHelps: 'Lentils are high in fiber and protein with a low glycemic index, helping blunt blood sugar spikes — useful for managing insulin resistance common in PCOS.',
  ),
  PcosRecipe(
    id: 'in_palak_paneer_lite',
    title: 'Light Palak Paneer (Spinach & Cottage Cheese)',
    cuisine: Cuisine.indian,
    mealType: MealType.dinner,
    tags: [PcosTag.highProtein, PcosTag.antiInflammatory, PcosTag.lowGi],
    description: 'A lighter version of the classic, using less cream and more spinach for an iron- and protein-rich dinner.',
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 3,
    ingredients: const [
      RecipeIngredient(name: 'Fresh spinach leaves', amount: '500 g'),
      RecipeIngredient(name: 'Paneer (cottage cheese), cubed', amount: '200 g'),
      RecipeIngredient(name: 'Onion, chopped', amount: '1 medium'),
      RecipeIngredient(name: 'Tomato, chopped', amount: '1 medium'),
      RecipeIngredient(name: 'Garlic cloves', amount: '3'),
      RecipeIngredient(name: 'Ginger', amount: '1 inch piece'),
      RecipeIngredient(name: 'Green chili', amount: '1'),
      RecipeIngredient(name: 'Cumin seeds', amount: '1 tsp'),
      RecipeIngredient(name: 'Garam masala', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Greek yogurt or low-fat cream', amount: '2 tbsp', note: 'in place of heavy cream'),
      RecipeIngredient(name: 'Olive oil', amount: '1 tbsp'),
      RecipeIngredient(name: 'Salt', amount: 'to taste'),
    ],
    steps: const [
      'Blanch the spinach in boiling water for 2 minutes, then transfer to cold water, drain, and blend into a coarse purée.',
      'Heat oil in a pan, add cumin seeds, then sauté onion until translucent.',
      'Add ginger, garlic, and green chili; cook 1 minute, then add tomato and cook until soft.',
      'Stir in the spinach purée, garam masala, and salt. Simmer 5 minutes.',
      'Fold in the paneer cubes and yogurt/cream, simmer 3–4 more minutes without boiling hard.',
      'Serve with a small portion of brown rice or one whole-wheat roti.',
    ],
    whyItHelps: 'Leafy greens bring anti-inflammatory antioxidants, while paneer offers protein that helps slow carbohydrate absorption at the meal.',
  ),
  PcosRecipe(
    id: 'in_ragi_dosa',
    title: 'Ragi (Finger Millet) Dosa',
    cuisine: Cuisine.indian,
    mealType: MealType.breakfast,
    tags: [PcosTag.lowGi, PcosTag.highFiber],
    description: 'A South Indian millet crepe that swaps refined rice for fiber-rich ragi flour.',
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Ragi (finger millet) flour', amount: '1 cup'),
      RecipeIngredient(name: 'Whole wheat flour', amount: '1/4 cup'),
      RecipeIngredient(name: 'Onion, finely chopped', amount: '1 small'),
      RecipeIngredient(name: 'Green chili, minced', amount: '1'),
      RecipeIngredient(name: 'Cumin seeds', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Curry leaves, chopped', amount: '5–6 leaves'),
      RecipeIngredient(name: 'Water', amount: '2 to 2.5 cups', note: 'to make a thin, pourable batter'),
      RecipeIngredient(name: 'Salt', amount: 'to taste'),
      RecipeIngredient(name: 'Oil', amount: '1 tbsp', note: 'for cooking'),
    ],
    steps: const [
      'Whisk ragi flour, wheat flour, water, and salt into a thin, lump-free batter. Let it rest 15 minutes.',
      'Stir in onion, chili, cumin, and curry leaves.',
      'Heat a flat pan, lightly oil it, then pour batter from the edge inward in a thin layer (it should be thinner than a pancake batter).',
      'Drizzle a little oil around the edges, cook until the base turns crisp and golden, about 2–3 minutes.',
      'Fold in half and serve with coconut chutney or sambar.',
    ],
    whyItHelps: 'Millets like ragi digest more slowly than refined grains, giving a gentler blood sugar response that supports insulin sensitivity.',
  ),
  PcosRecipe(
    id: 'in_chickpea_salad',
    title: 'Spiced Chana (Chickpea) Salad',
    cuisine: Cuisine.indian,
    mealType: MealType.lunch,
    tags: [PcosTag.highFiber, PcosTag.highProtein, PcosTag.lowGi],
    description: 'A cooling, protein-packed chickpea salad eaten across Indian households as a light lunch or snack.',
    prepMinutes: 15,
    cookMinutes: 0,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Boiled chickpeas (kabuli chana)', amount: '2 cups'),
      RecipeIngredient(name: 'Cucumber, diced', amount: '1 medium'),
      RecipeIngredient(name: 'Tomato, diced', amount: '1 medium'),
      RecipeIngredient(name: 'Red onion, finely chopped', amount: '1/2 medium'),
      RecipeIngredient(name: 'Lemon juice', amount: '2 tbsp'),
      RecipeIngredient(name: 'Chaat masala', amount: '1 tsp'),
      RecipeIngredient(name: 'Roasted cumin powder', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Fresh coriander, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Olive oil', amount: '1 tsp'),
      RecipeIngredient(name: 'Salt', amount: 'to taste'),
    ],
    steps: const [
      'In a large bowl, combine the chickpeas, cucumber, tomato, and onion.',
      'Add lemon juice, chaat masala, cumin powder, olive oil, and salt.',
      'Toss well, top with coriander, and chill for 10 minutes before serving for best flavor.',
    ],
    whyItHelps: 'Chickpeas combine plant protein and soluble fiber, both linked to steadier blood sugar and improved satiety.',
  ),
  PcosRecipe(
    id: 'in_masala_oats',
    title: 'Vegetable Masala Oats',
    cuisine: Cuisine.indian,
    mealType: MealType.breakfast,
    tags: [PcosTag.highFiber, PcosTag.lowGi],
    description: 'A savory Indian-spiced take on oatmeal loaded with vegetables.',
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 1,
    ingredients: const [
      RecipeIngredient(name: 'Rolled oats', amount: '1/2 cup'),
      RecipeIngredient(name: 'Mixed vegetables (carrot, beans, peas), diced', amount: '1/2 cup'),
      RecipeIngredient(name: 'Onion, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Mustard seeds', amount: '1/4 tsp'),
      RecipeIngredient(name: 'Curry leaves', amount: '4–5'),
      RecipeIngredient(name: 'Turmeric powder', amount: 'a pinch'),
      RecipeIngredient(name: 'Water or vegetable stock', amount: '1.5 cups'),
      RecipeIngredient(name: 'Olive oil', amount: '1 tsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Heat oil, add mustard seeds and curry leaves, let them sizzle.',
      'Add onion and vegetables, sauté 3–4 minutes until just tender.',
      'Add turmeric, then the oats, and stir for a minute to toast lightly.',
      'Pour in water/stock, season, and simmer 4–5 minutes until creamy and the oats are cooked through.',
    ],
    whyItHelps: 'Oats are a beta-glucan-rich soluble fiber source shown to help moderate post-meal blood sugar response.',
  ),
];
