import 'recipe_models.dart';

/// East Asian–cuisine PCOS-friendly recipes.
final List<PcosRecipe> eastAsianRecipes = [
  PcosRecipe(
    id: 'ea_tofu_stirfry',
    title: 'Ginger Garlic Tofu & Vegetable Stir-Fry',
    cuisine: Cuisine.eastAsian,
    mealType: MealType.dinner,
    tags: [PcosTag.highProtein, PcosTag.lowGi, PcosTag.antiInflammatory],
    description: 'A quick weeknight stir-fry built around plant protein and crunchy vegetables.',
    prepMinutes: 15,
    cookMinutes: 10,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Firm tofu, cubed', amount: '300 g'),
      RecipeIngredient(name: 'Broccoli florets', amount: '1 cup'),
      RecipeIngredient(name: 'Carrot, sliced thin', amount: '1 medium'),
      RecipeIngredient(name: 'Bell pepper, sliced', amount: '1 medium'),
      RecipeIngredient(name: 'Garlic cloves, minced', amount: '2'),
      RecipeIngredient(name: 'Ginger, grated', amount: '1 tbsp'),
      RecipeIngredient(name: 'Low-sodium soy sauce', amount: '2 tbsp'),
      RecipeIngredient(name: 'Sesame oil', amount: '1 tbsp'),
      RecipeIngredient(name: 'Rice vinegar', amount: '1 tsp'),
      RecipeIngredient(name: 'Sesame seeds', amount: '1 tsp', note: 'to garnish'),
      RecipeIngredient(name: 'Cornstarch', amount: '1 tsp', note: 'optional, for crisping tofu'),
    ],
    steps: const [
      'Pat tofu dry, toss lightly in cornstarch if using, and pan-fry in a little oil until golden on all sides. Set aside.',
      'In the same pan, add sesame oil, then garlic and ginger; sauté 30 seconds.',
      'Add broccoli, carrot, and bell pepper; stir-fry 4–5 minutes until just tender-crisp.',
      'Return tofu to the pan, add soy sauce and rice vinegar, toss to coat.',
      'Garnish with sesame seeds and serve with a small portion of brown rice.',
    ],
    whyItHelps: 'Tofu is a complete plant protein, and the high vegetable-to-starch ratio keeps the meal\'s overall glycemic load lower.',
  ),
  PcosRecipe(
    id: 'ea_miso_salmon_bowl',
    title: 'Miso-Glazed Salmon Rice Bowl',
    cuisine: Cuisine.eastAsian,
    mealType: MealType.dinner,
    tags: [PcosTag.highProtein, PcosTag.antiInflammatory, PcosTag.hormoneSupportive],
    description: 'A Japanese-inspired bowl pairing omega-3-rich salmon with fermented miso flavor.',
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Salmon fillets', amount: '2 (about 150 g each)'),
      RecipeIngredient(name: 'Miso paste', amount: '2 tbsp'),
      RecipeIngredient(name: 'Soy sauce', amount: '1 tbsp'),
      RecipeIngredient(name: 'Honey or maple syrup', amount: '1 tsp'),
      RecipeIngredient(name: 'Brown rice, cooked', amount: '1.5 cups'),
      RecipeIngredient(name: 'Edamame, shelled', amount: '1/2 cup'),
      RecipeIngredient(name: 'Cucumber, sliced', amount: '1/2'),
      RecipeIngredient(name: 'Spring onion, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Sesame seeds', amount: '1 tsp'),
    ],
    steps: const [
      'Mix miso paste, soy sauce, and honey into a glaze.',
      'Brush the glaze over the salmon and let marinate 10 minutes if time allows.',
      'Pan-sear or bake the salmon (200°C / 390°F for about 12 minutes) until just cooked through.',
      'Assemble bowls with brown rice as the base, then top with salmon, edamame, cucumber, spring onion, and sesame seeds.',
    ],
    whyItHelps: 'Fermented miso supports gut health, while salmon\'s omega-3s and edamame\'s plant protein round out a balanced, anti-inflammatory plate.',
  ),
  PcosRecipe(
    id: 'ea_egg_drop_veg_soup',
    title: 'Egg Drop Vegetable Soup',
    cuisine: Cuisine.eastAsian,
    mealType: MealType.lunch,
    tags: [PcosTag.highProtein, PcosTag.lowGi],
    description: 'A light, fast Chinese-style soup that works well as a starter or simple lunch.',
    prepMinutes: 10,
    cookMinutes: 10,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Vegetable or chicken stock', amount: '4 cups'),
      RecipeIngredient(name: 'Eggs, beaten', amount: '2'),
      RecipeIngredient(name: 'Carrot, julienned', amount: '1/2 cup'),
      RecipeIngredient(name: 'Mushrooms, sliced', amount: '1/2 cup'),
      RecipeIngredient(name: 'Spinach or bok choy, chopped', amount: '1 cup'),
      RecipeIngredient(name: 'Ginger, grated', amount: '1 tsp'),
      RecipeIngredient(name: 'Soy sauce', amount: '1 tbsp'),
      RecipeIngredient(name: 'Cornstarch slurry (1 tsp cornstarch + 1 tbsp water)', amount: '1 tbsp', note: 'optional, to thicken'),
      RecipeIngredient(name: 'Spring onion, chopped', amount: '2 tbsp'),
    ],
    steps: const [
      'Bring stock to a simmer with ginger and soy sauce.',
      'Add carrot and mushrooms, cook 3–4 minutes until just tender.',
      'Stir in the cornstarch slurry if using, to lightly thicken.',
      'Reduce to a gentle simmer and slowly drizzle in the beaten eggs while stirring in one direction to form ribbons.',
      'Add greens, cook 1 more minute, and top with spring onion before serving.',
    ],
    whyItHelps: 'A high-protein, low-starch soup like this is a good way to add volume and nutrients to a meal without much glycemic impact.',
  ),
  PcosRecipe(
    id: 'ea_buckwheat_noodle_salad',
    title: 'Cold Buckwheat (Soba) Noodle Salad',
    cuisine: Cuisine.eastAsian,
    mealType: MealType.lunch,
    tags: [PcosTag.lowGi, PcosTag.highFiber],
    description: 'A Japanese-style cold noodle salad using fiber-rich buckwheat soba instead of refined noodles.',
    prepMinutes: 15,
    cookMinutes: 10,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Soba (buckwheat) noodles', amount: '150 g'),
      RecipeIngredient(name: 'Cucumber, julienned', amount: '1/2'),
      RecipeIngredient(name: 'Carrot, julienned', amount: '1/2'),
      RecipeIngredient(name: 'Edamame, shelled', amount: '1/3 cup'),
      RecipeIngredient(name: 'Soy sauce', amount: '2 tbsp'),
      RecipeIngredient(name: 'Rice vinegar', amount: '1 tbsp'),
      RecipeIngredient(name: 'Sesame oil', amount: '1 tbsp'),
      RecipeIngredient(name: 'Sesame seeds', amount: '1 tsp'),
      RecipeIngredient(name: 'Spring onion, chopped', amount: '2 tbsp'),
    ],
    steps: const [
      'Cook soba noodles per package instructions, then rinse under cold water to stop cooking and remove excess starch.',
      'Whisk soy sauce, rice vinegar, and sesame oil for the dressing.',
      'Toss noodles with cucumber, carrot, edamame, and dressing.',
      'Top with sesame seeds and spring onion, then chill briefly before serving.',
    ],
    whyItHelps: 'Buckwheat is a fiber-rich, gluten-free grain with a lower glycemic index than refined wheat noodles.',
  ),
];
