import 'recipe_models.dart';

/// Mediterranean-cuisine PCOS-friendly recipes.
final List<PcosRecipe> mediterraneanRecipes = [
  PcosRecipe(
    id: 'med_greek_salad_chicken',
    title: 'Greek Salad with Grilled Chicken',
    cuisine: Cuisine.mediterranean,
    mealType: MealType.lunch,
    tags: [PcosTag.antiInflammatory, PcosTag.highProtein, PcosTag.lowGi],
    description: 'A classic Mediterranean salad built around healthy fats, fiber, and lean protein.',
    prepMinutes: 15,
    cookMinutes: 10,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Chicken breast', amount: '250 g'),
      RecipeIngredient(name: 'Cucumber, chopped', amount: '1 medium'),
      RecipeIngredient(name: 'Tomato, chopped', amount: '2 medium'),
      RecipeIngredient(name: 'Red onion, thinly sliced', amount: '1/2 medium'),
      RecipeIngredient(name: 'Kalamata olives', amount: '1/4 cup'),
      RecipeIngredient(name: 'Feta cheese, cubed', amount: '60 g'),
      RecipeIngredient(name: 'Extra virgin olive oil', amount: '2 tbsp'),
      RecipeIngredient(name: 'Red wine vinegar', amount: '1 tbsp'),
      RecipeIngredient(name: 'Dried oregano', amount: '1 tsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Season the chicken breast with salt, pepper, and a little oregano, then grill or pan-sear about 5–6 minutes per side until cooked through. Let rest, then slice.',
      'In a large bowl, combine cucumber, tomato, onion, and olives.',
      'Whisk olive oil, vinegar, oregano, salt, and pepper for the dressing.',
      'Toss the vegetables with the dressing, top with feta and sliced chicken.',
    ],
    whyItHelps: 'Olive oil and fatty components support an anti-inflammatory fat profile, while lean chicken adds protein to slow the meal\'s glycemic impact.',
  ),
  PcosRecipe(
    id: 'med_lentil_soup',
    title: 'Mediterranean Red Lentil Soup',
    cuisine: Cuisine.mediterranean,
    mealType: MealType.dinner,
    tags: [PcosTag.highFiber, PcosTag.highProtein, PcosTag.lowGi],
    description: 'A warming, fiber-dense soup common across Greek, Turkish, and Levantine kitchens.',
    prepMinutes: 10,
    cookMinutes: 30,
    servings: 4,
    ingredients: const [
      RecipeIngredient(name: 'Red lentils, rinsed', amount: '1 cup'),
      RecipeIngredient(name: 'Onion, chopped', amount: '1 medium'),
      RecipeIngredient(name: 'Carrot, chopped', amount: '1 medium'),
      RecipeIngredient(name: 'Garlic cloves, minced', amount: '2'),
      RecipeIngredient(name: 'Cumin powder', amount: '1 tsp'),
      RecipeIngredient(name: 'Smoked paprika', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Vegetable stock', amount: '4 cups'),
      RecipeIngredient(name: 'Lemon juice', amount: '1 tbsp'),
      RecipeIngredient(name: 'Olive oil', amount: '2 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Heat olive oil in a pot, sauté onion and carrot until softened, about 5 minutes.',
      'Add garlic, cumin, and paprika; cook 1 minute until fragrant.',
      'Add lentils and stock, bring to a boil, then reduce heat and simmer 20–25 minutes until lentils are soft.',
      'Blend partially or fully for a creamy texture (optional), then finish with lemon juice, salt, and pepper.',
    ],
    whyItHelps: 'Red lentils are rich in plant protein and fiber, supporting more stable post-meal blood sugar and longer satiety.',
  ),
  PcosRecipe(
    id: 'med_shakshuka',
    title: 'Shakshuka (Eggs in Spiced Tomato Sauce)',
    cuisine: Cuisine.mediterranean,
    mealType: MealType.breakfast,
    tags: [PcosTag.highProtein, PcosTag.antiInflammatory],
    description: 'A North African–Mediterranean breakfast of eggs poached in a richly spiced tomato sauce.',
    prepMinutes: 10,
    cookMinutes: 20,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Eggs', amount: '4'),
      RecipeIngredient(name: 'Crushed tomatoes', amount: '400 g (1 can)'),
      RecipeIngredient(name: 'Onion, diced', amount: '1 small'),
      RecipeIngredient(name: 'Bell pepper, diced', amount: '1 medium'),
      RecipeIngredient(name: 'Garlic cloves, minced', amount: '2'),
      RecipeIngredient(name: 'Cumin powder', amount: '1 tsp'),
      RecipeIngredient(name: 'Paprika', amount: '1 tsp'),
      RecipeIngredient(name: 'Chili flakes', amount: 'a pinch, optional'),
      RecipeIngredient(name: 'Olive oil', amount: '2 tbsp'),
      RecipeIngredient(name: 'Fresh parsley, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Heat olive oil in a wide skillet, sauté onion and bell pepper until soft, about 5 minutes.',
      'Add garlic, cumin, paprika, and chili flakes; cook 1 minute.',
      'Pour in crushed tomatoes, season, and simmer 10 minutes until thickened.',
      'Make small wells in the sauce and crack in the eggs. Cover and cook 5–8 minutes until whites are set but yolks remain soft.',
      'Garnish with parsley and serve with whole-grain bread.',
    ],
    whyItHelps: 'Eggs deliver high-quality protein and choline, while tomatoes provide lycopene, an antioxidant studied for its anti-inflammatory potential.',
  ),
  PcosRecipe(
    id: 'med_baked_salmon',
    title: 'Baked Salmon with Herbs and Lemon',
    cuisine: Cuisine.mediterranean,
    mealType: MealType.dinner,
    tags: [PcosTag.antiInflammatory, PcosTag.highProtein, PcosTag.hormoneSupportive],
    description: 'Simple oven-baked salmon, a Mediterranean diet staple known for its omega-3 content.',
    prepMinutes: 10,
    cookMinutes: 15,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Salmon fillets', amount: '2 (about 150 g each)'),
      RecipeIngredient(name: 'Extra virgin olive oil', amount: '1 tbsp'),
      RecipeIngredient(name: 'Lemon, sliced', amount: '1'),
      RecipeIngredient(name: 'Garlic cloves, minced', amount: '2'),
      RecipeIngredient(name: 'Fresh dill or parsley', amount: '2 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Preheat oven to 200°C (390°F).',
      'Place salmon on a lined baking tray, drizzle with olive oil, and rub with garlic, salt, and pepper.',
      'Top with lemon slices and herbs.',
      'Bake 12–15 minutes until just opaque and flaky.',
      'Serve with a side of steamed greens or a small portion of quinoa.',
    ],
    whyItHelps: 'Omega-3 fatty acids in salmon are studied for supporting reduced inflammation, which can be elevated in PCOS.',
  ),
];
