import 'recipe_models.dart';

/// Western-cuisine PCOS-friendly recipes.
final List<PcosRecipe> westernRecipes = [
  PcosRecipe(
    id: 'we_overnight_oats',
    title: 'Cinnamon Berry Overnight Oats',
    cuisine: Cuisine.western,
    mealType: MealType.breakfast,
    tags: [PcosTag.highFiber, PcosTag.lowGi],
    description: 'A no-cook, make-ahead breakfast that keeps mornings simple without reaching for refined cereal.',
    prepMinutes: 10,
    cookMinutes: 0,
    servings: 1,
    ingredients: const [
      RecipeIngredient(name: 'Rolled oats', amount: '1/2 cup'),
      RecipeIngredient(name: 'Unsweetened almond milk (or milk of choice)', amount: '1/2 cup'),
      RecipeIngredient(name: 'Greek yogurt', amount: '1/4 cup'),
      RecipeIngredient(name: 'Chia seeds', amount: '1 tbsp'),
      RecipeIngredient(name: 'Cinnamon powder', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Mixed berries (fresh or frozen)', amount: '1/2 cup'),
      RecipeIngredient(name: 'Walnuts or almonds, chopped', amount: '1 tbsp'),
    ],
    steps: const [
      'In a jar, combine oats, almond milk, yogurt, chia seeds, and cinnamon. Stir well.',
      'Cover and refrigerate overnight (or at least 4 hours).',
      'In the morning, top with berries and nuts before eating.',
    ],
    whyItHelps: 'Chia and oats together bring soluble fiber and slow-digesting carbohydrates, while Greek yogurt adds protein for a more balanced glycemic response.',
  ),
  PcosRecipe(
    id: 'we_quinoa_buddha_bowl',
    title: 'Quinoa & Roasted Vegetable Buddha Bowl',
    cuisine: Cuisine.western,
    mealType: MealType.lunch,
    tags: [PcosTag.highFiber, PcosTag.highProtein, PcosTag.lowGi],
    description: 'A balanced, build-your-own bowl built on a complete-protein grain.',
    prepMinutes: 15,
    cookMinutes: 25,
    servings: 2,
    ingredients: const [
      RecipeIngredient(name: 'Quinoa, rinsed', amount: '1 cup'),
      RecipeIngredient(name: 'Sweet potato, cubed', amount: '1 medium'),
      RecipeIngredient(name: 'Broccoli florets', amount: '1 cup'),
      RecipeIngredient(name: 'Chickpeas, drained and rinsed', amount: '1 cup'),
      RecipeIngredient(name: 'Olive oil', amount: '2 tbsp'),
      RecipeIngredient(name: 'Paprika', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Tahini', amount: '2 tbsp'),
      RecipeIngredient(name: 'Lemon juice', amount: '1 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Preheat oven to 200°C (390°F). Toss sweet potato, broccoli, and chickpeas with 1 tbsp olive oil, paprika, salt, and pepper.',
      'Roast 20–25 minutes, tossing halfway, until vegetables are caramelized and chickpeas are slightly crisp.',
      'Meanwhile, cook quinoa according to package directions (typically 1 cup quinoa to 2 cups water, simmered ~15 minutes).',
      'Whisk tahini, lemon juice, remaining olive oil, and a splash of water into a dressing.',
      'Assemble bowls with quinoa as the base, top with roasted vegetables and chickpeas, and drizzle with tahini dressing.',
    ],
    whyItHelps: 'Quinoa is a complete protein and fiber source, and roasting vegetables instead of frying keeps added fat moderate and nutrient-dense.',
  ),
  PcosRecipe(
    id: 'we_turkey_chili',
    title: 'Lean Turkey & Bean Chili',
    cuisine: Cuisine.western,
    mealType: MealType.dinner,
    tags: [PcosTag.highProtein, PcosTag.highFiber, PcosTag.lowGi],
    description: 'A hearty, slow-simmered chili that leans on lean protein and beans rather than refined carbs.',
    prepMinutes: 15,
    cookMinutes: 35,
    servings: 4,
    ingredients: const [
      RecipeIngredient(name: 'Lean ground turkey', amount: '500 g'),
      RecipeIngredient(name: 'Onion, diced', amount: '1 medium'),
      RecipeIngredient(name: 'Bell pepper, diced', amount: '1 medium'),
      RecipeIngredient(name: 'Garlic cloves, minced', amount: '3'),
      RecipeIngredient(name: 'Crushed tomatoes', amount: '400 g (1 can)'),
      RecipeIngredient(name: 'Kidney beans, drained', amount: '400 g (1 can)'),
      RecipeIngredient(name: 'Black beans, drained', amount: '400 g (1 can)'),
      RecipeIngredient(name: 'Chili powder', amount: '1 tbsp'),
      RecipeIngredient(name: 'Cumin powder', amount: '1 tsp'),
      RecipeIngredient(name: 'Smoked paprika', amount: '1/2 tsp'),
      RecipeIngredient(name: 'Olive oil', amount: '1 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
    ],
    steps: const [
      'Heat olive oil in a large pot, brown the turkey, breaking it up as it cooks, about 5–6 minutes.',
      'Add onion, bell pepper, and garlic; cook until softened, about 5 minutes.',
      'Stir in chili powder, cumin, and paprika; cook 1 minute until fragrant.',
      'Add crushed tomatoes and both types of beans. Simmer uncovered 20–25 minutes, stirring occasionally, until thickened.',
      'Season to taste and serve, optionally with a small dollop of Greek yogurt instead of sour cream.',
    ],
    whyItHelps: 'Beans bring a strong dose of fiber and resistant starch, both linked to gentler post-meal blood sugar response, paired with lean protein from turkey.',
  ),
  PcosRecipe(
    id: 'we_zucchini_egg_muffins',
    title: 'Zucchini & Egg Breakfast Muffins',
    cuisine: Cuisine.western,
    mealType: MealType.breakfast,
    tags: [PcosTag.highProtein, PcosTag.lowGi],
    description: 'Make-ahead, grab-and-go protein muffins, great for busy mornings.',
    prepMinutes: 15,
    cookMinutes: 20,
    servings: 4,
    ingredients: const [
      RecipeIngredient(name: 'Eggs', amount: '6'),
      RecipeIngredient(name: 'Zucchini, grated and squeezed dry', amount: '1 medium'),
      RecipeIngredient(name: 'Spinach, chopped', amount: '1 cup'),
      RecipeIngredient(name: 'Feta cheese, crumbled', amount: '1/4 cup'),
      RecipeIngredient(name: 'Spring onion, chopped', amount: '2 tbsp'),
      RecipeIngredient(name: 'Salt and pepper', amount: 'to taste'),
      RecipeIngredient(name: 'Olive oil', amount: '1 tsp', note: 'for greasing the muffin tin'),
    ],
    steps: const [
      'Preheat oven to 180°C (350°F) and lightly grease a 12-cup muffin tin.',
      'Whisk eggs in a large bowl, then stir in zucchini, spinach, feta, spring onion, salt, and pepper.',
      'Divide the mixture evenly among muffin cups.',
      'Bake 18–20 minutes until set and lightly golden on top.',
      'Cool slightly before removing. Store in the fridge for up to 4 days for quick breakfasts.',
    ],
    whyItHelps: 'A protein-forward breakfast like this helps reduce mid-morning blood sugar swings compared to carb-heavy options like pastries or sugary cereal.',
  ),
];
